---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
              - 5000:5000
        image: brauliolpx/iss_tracker:project
        volumes:
            - ./config.yaml:/config.yaml
